name: Publish tree-sitter-stack-graphs release

on:
  push:
    tags:
      - tree-sitter-stack-graphs-v*

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      CRATE_DIR: './tree-sitter-stack-graphs'
    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@v1
      - name: Checkout repository
        uses: actions/checkout@v2
      # TODO Verify the crate version matches the tag
      - name: Verify publish crate
        uses: katyo/publish-crates@v1
        with:
          path: ${{ env.CRATE_DIR }}
          dry-run: true
      - name: Publish crate
        uses: katyo/publish-crates@v1
        with:
          path: ${{ env.CRATE_DIR }}
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish-npm:
    runs-on: ubuntu-latest
    env:
      PACKAGE_DIR: './tree-sitter-stack-graphs/npm'
    steps:
      - name: Install Node environment
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - name: Checkout repository
        uses: actions/checkout@v3
      # TODO Verify the package version matches the tag
      - name: Verify package
        run: npm publish --dry-run ${{ env.PACKAGE_DIR }}
      - name: Publish package
        run: npm publish ${{ env.PACKAGE_DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
